using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroMEMSApp.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Xml.Linq;

    // https://stackoverflow.com/questions/32015348/dataannotations-support-in-windows-forms
    [Table("TBYT")]
    public partial class TBYT
    {
        public TBYT()
        {
            this.TBYT_LK = new HashSet<TBYT_LK>();
        }

        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Nhom Thiet Bi")]
        public string NhomTB { get; set; }

        [Display(Name = "Loai Thiet Bi")]
        public string LoaiTB { get; set; }

        [Display(Name = "Ma Thiet Bi")]
        public string MaTB { get; set; }

        [Display(Name = "Ten Thiet Bi")]
        public string TenTB { get; set; }

        [Display(Name = "Don vi tinh")]
        public string Dvt { get; set; }

        [Display(Name = "Hang San Xuat")]
        public string HangSX { get; set; }

        [Display(Name = "Nuoc San Xuat")]
        public string NuocSX { get; set; }

        [Display(Name = "Nam San Xuat")]
        public int NamSX { get; set; }

        [Display(Name = "Gia Tri")]
        public int GiaTri { get; set; }

        [Display(Name = "So Lan Bao Tri Mot Nam")]
        public int SoLanBaoTriMotNam { get; set; }

        [Display(AutoGenerateField = false)]
        public virtual ICollection<TBYT_LK> TBYT_LK { get; set; }
    }
}
