//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroMEMSApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBYT_Table
    {
        public TBYT_Table()
        {
            this.LKTBYT_Table = new HashSet<LKTBYT_Table>();
        }
    
        public int Id { get; set; }
        public string NhomTB { get; set; }
        public string LoaiTB { get; set; }
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public string Dvt { get; set; }
        public string HangSX { get; set; }
        public string NuocSX { get; set; }
        public int NamSX { get; set; }
        public int GiaTri { get; set; }
        public int SoLanBaoTriMotNam { get; set; }
    
        public virtual ICollection<LKTBYT_Table> LKTBYT_Table { get; set; }
    }
}
